routes/web.php
<?php

use App\Http\Controllers\admin\AdminUserController;
use App\Http\Controllers\admin\AdminMovieController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [HomeController::class, 'index'])->name('home');

Route::get("/users/login", [UserController::class, 'login'])->name('user.get.login');
Route::post('/users/login', [UserController::class, 'postLogin'])->name('user.post.login');
Route::get('/users/logout', [UserController::class, 'postLogout'])->name('user.get.logout');

Route::get("/users/register", [UserController::class, 'register'])->name('user.create');
Route::post("/users", [UserController::class, 'store'])->name('user.store');

Route::get('/blog/create', [MovieController::class, 'create'])->name('blog.create');
Route::post('/blog/create', [MovieController::class, 'store'])->name('blog.create');

Route::get('/blog/show/{id}', [MovieController::class, 'show'])->name('blog.show');
Route::get('/blog/{id}/comment', [MovieController::class, 'leaveComment'])->name('blog.leave.comment');
Route::post('/blog/{id}/post/comment', [MovieController::class, 'postComment'])->name('blog.post.comment');
Route::get('/blog/edit/{id}', [MovieController::class, 'getEdit'])->name('blog.get.edit');
Route::post('/blog/edit/{id}', [MovieController::class, 'postEdit'])->name('blog.post.edit');

Route::get('/contact-us', [HomeController::class, 'contact'])->name('contact');
Route::post('/message', [HomeController::class, 'sendMessage'])->name('post.contact');

//admin panel
Route::get('/adminpanel', [AdminController::class, 'index'])->name('adminpanel')->middleware('admin');

//crud users
Route::get('adminpanel/users', [AdminUserController::class, 'index'])->name('users')->middleware('admin');
Route::get('adminpanel/users/create', [AdminUserController::class, 'create'])->name('add-user')->middleware('admin');
Route::post('adminpanel/users/store', [AdminUserController::class, 'store'])->name('store-user')->middleware('admin');
Route::get('adminpanel/users/edit/{id}', [AdminUserController::class, 'edit'])->name('edit-user')->middleware('admin');
Route::post('adminpanel/users/update/{id}', [AdminUserController::class, 'update'])->name('update-user')->middleware('admin');
Route::delete('adminpanel/users/delete/{id}', [AdminUserController::class, 'destroy'])->name('delete-user')->middleware('admin');

// crud za filmove,
Route::resource('adminpanel/movies', 'admin\AdminMovieController')->middleware('admin');

//crud za logove
Route::resource('adminpanel/logs', 'admin\AdminLogController')->middleware('admin');

resources/views/admin/panel.blade.php
@extends('admin.layouts.admin-layout')

@section('content')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Dashboard</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- Small boxes (Stat box) -->
                    <div class="row">
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-warning">
                                <div class="inner">
                                    <h3>{{count($users)}}</h3>

                                    <p>Users</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-person-add"></i>
                                </div>
                                <a href="/adminpanel/users" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-success">
                                <div class="inner">
                                    <h3>{{count($movies)}}</h3>

                                    <p>Movies</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                                <a href="/adminpanel/movies" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-danger">
                                <div class="inner">
                                    <h3>{{count($logs)}}</h3>

                                    <p>Logs</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-pie-graph"></i>
                                </div>
                                <a href="/adminpanel/logs" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <!-- ./col -->
                    </div>
                    <!-- /.row -->
                    <!-- Main row -->
                    <div class="row">
                        <!-- Left col -->
                        <section class="col-lg-12 connectedSortable">
                            <!-- Custom tabs (Charts with tabs)-->
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="fas fa-chart-pie mr-1"></i>
                                        Activities
                                    </h3>
                                </div><!-- /.card-header -->
                                <div class="card-body">
                                    <div class="tab-content p-0">
                                        <!-- Morris chart - Sales -->
                                        <div class="chart tab-pane active" id="revenue-chart"
                                             style="position: relative; height: 300px;">
                                            <div class="card">
                                                <div class="card-body">
                                                    <table id="example1" class="table table-bordered table-striped">
                                                        <thead>
                                                        <tr>
                                                            <th>Id</th>
                                                            <th>Action</th>
                                                            <th>user_id</th>
                                                            <th>Movie_id</th>
                                                            <th>Options</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        @foreach($logs as $c)
                                                            <tr>
                                                                <td>{{$c->id}}</td>
                                                                <td>{{$c->action}}</td>
                                                                <td>{{$c->user_id}}</td>
                                                                <td>{{$c->movie_id}}</td>
                                                                <td>
                                                                    <form action="{{ route('logs.destroy', $c->id) }}" method="DELETE">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit" onclick=" return confirm('Da li sigurno brisete?')" title="Delete" class="btn btn-md btn-danger" >Delete</button>
                                                                    </form>
                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                        </tbody>
                                                        <tfoot>
                                                        <tr>
                                                            <th>Id</th>
                                                            <th>Action</th>
                                                            <th>user_id</th>
                                                            <th>Movie_id</th>
                                                            <th>Options</th>

                                                        </tr>
                                                        </tfoot>
                                                    </table>
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                        </div>
                                        <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;">
                                            <canvas id="sales-chart-canvas" height="300" style="height: 300px;"></canvas>
                                        </div>
                                    </div>
                                </div><!-- /.card-body -->
                            </div>
                            <!-- /.card -->




                        </section>
                        <!-- /.Left col -->

                    </div>
                    <!-- /.row (main row) -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>

    @endsection