routes/web.php
<?php

use App\Http\Controllers\admin\AdminUserController;
use App\Http\Controllers\admin\AdminMovieController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [HomeController::class, 'index'])->name('home');

Route::get("/users/login", [UserController::class, 'login'])->name('user.get.login');
Route::post('/users/login', [UserController::class, 'postLogin'])->name('user.post.login');
Route::get('/users/logout', [UserController::class, 'postLogout'])->name('user.get.logout');

Route::get("/users/register", [UserController::class, 'register'])->name('user.create');
Route::post("/users", [UserController::class, 'store'])->name('user.store');

Route::get('/blog/create', [MovieController::class, 'create'])->name('blog.create');
Route::post('/blog/create', [MovieController::class, 'store'])->name('blog.create');

Route::get('/blog/show/{id}', [MovieController::class, 'show'])->name('blog.show');
Route::get('/blog/{id}/comment', [MovieController::class, 'leaveComment'])->name('blog.leave.comment');
Route::post('/blog/{id}/post/comment', [MovieController::class, 'postComment'])->name('blog.post.comment');
Route::get('/blog/edit/{id}', [MovieController::class, 'getEdit'])->name('blog.get.edit');
Route::post('/blog/edit/{id}', [MovieController::class, 'postEdit'])->name('blog.post.edit');

Route::get('/contact-us', [HomeController::class, 'contact'])->name('contact');
Route::post('/message', [HomeController::class, 'sendMessage'])->name('post.contact');

//admin panel
Route::get('/adminpanel', [AdminController::class, 'index'])->name('adminpanel')->middleware('admin');

//crud users
Route::get('adminpanel/users', [AdminUserController::class, 'index'])->name('users')->middleware('admin');
Route::get('adminpanel/users/create', [AdminUserController::class, 'create'])->name('add-user')->middleware('admin');
Route::post('adminpanel/users/store', [AdminUserController::class, 'store'])->name('store-user')->middleware('admin');
Route::get('adminpanel/users/edit/{id}', [AdminUserController::class, 'edit'])->name('edit-user')->middleware('admin');
Route::post('adminpanel/users/update/{id}', [AdminUserController::class, 'update'])->name('update-user')->middleware('admin');
Route::delete('adminpanel/users/delete/{id}', [AdminUserController::class, 'destroy'])->name('delete-user')->middleware('admin');

// crud za filmove,
Route::resource('adminpanel/movies', 'admin\AdminMovieController')->middleware('admin');

//crud za logove
Route::resource('adminpanel/logs', 'admin\AdminLogController')->middleware('admin');

resources/views/admin/movies/create.blade.php
@extends('admin.layouts.admin-layout')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    Add Movie
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops! </strong> nije uspeo unos.<br>
                            <ul>
                                @foreach ($errors as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <form class="form form-group" action="{{route('movies.store')}}" method="post" enctype="multipart/form-data">
                                            @csrf
                                            <div class="form-group">
                                                <label>Title
                                                    <input type="text" class="form-control" name="title" >
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Short description
                                                    <textarea  name="short_description" class="form-control" rows="5" cols="30"></textarea>
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Long Description
                                                    <textarea  name="long_description" class="form-control" rows="5" cols="30"></textarea>
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label> Rating
                                                    <input type="text" class="form-control" name="rating" >
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Image
                                                    <input type="file" name="image_path">
                                                </label>
                                            </div>

                                            @method('post')
                                            <a href="{{route('movies.index')}}" class="btn btn-success">Back</a>
                                            <input type="submit" value="Add" class="pull-right btn btn-primary">
                                        </form>

                                    </div>
                                    {{--        </form>--}}

                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

@endsection

resources/views/admin/movies/edit.blade.php
@extends('admin.layouts.admin-layout')

@section('content')
{{--    {{dd($movie)}}--}}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    Add Movie
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops! </strong> nije uspeo unos.<br>
                            <ul>
                                @foreach ($errors as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <form class="form form-group" action="{{route('movies.update', $movie->id)}}" method="post" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <div class="form-group">
                                                <label>Title
                                                    <input type="text" class="form-control" name="title" value="{{$movie->title}}">
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Short description
                                                    <textarea  name="short_description" class="form-control" rows="5" cols="30">{{$movie->short_description}}</textarea>
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Long Description
                                                    <textarea  name="long_description" class="form-control" rows="5" cols="30">{{$movie->long_description}}</textarea>
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label> Rating
                                                    <input type="text" class="form-control" name="rating" value="{{$movie->rating}}">
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label>Image
                                                    <input type="file" name="image_path">
                                                </label>
                                            </div>
                                            <a href="{{route('movies.index')}}" class="btn btn-success">Back</a>
                                            <input type="submit" value="Add" class="pull-right btn btn-primary">
                                        </form>

                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

@endsection

resources/views/admin/movies/index.blade.php
@extends('admin.layouts.admin-layout')

@section('content')
            @include('admin.common.ajax', ['route' => url('/adminpanel/movies')])
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-3">
                        <h1>Movies</h1>

                    </div>

                    <div class="col-sm-3">
                        <a class="btn btn-sm btn-success" href="/adminpanel/movies/create">Add new</a>
                    </div>
                    <div class="col-sm-3">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-default-success">
                                <p>{{$message}}</p>
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops! </strong> nije uspeo unos.<br>
                            <ul>
                                @foreach ($errors as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Short desc</th>
                                        <th>Long desc</th>
                                        <th>Rating</th>
                                        <th>User</th>
                                        <th>Options</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($movies as $c)
                                        <tr id="object-{{$c->id}}">
                                            <td>{{$c->id}}</td>
                                            <td>{{$c->title}}</td>
                                            <td>{{$c->short_description}}</td>
                                            <td>{{$c->long_description }}</td>
                                            <td>{{$c->rating }}</td>
                                            <td>{{$c->user_id }}</td>
                                            <td>
                                                <form method="DELETE" class="delete-object">
                                                <a class="btn btn-md btn-info" href="{{route('movies.show',$c->id)}}">Show</a>
                                                <a class="btn btn-md btn-warning" href="{{route('movies.edit',$c->id)}}">Edit</a>
                                                @csrf
                                                @method('DELETE')
                                                <input type="hidden"  value="{{$c->id}}" id="object-id">
                                                <button type="submit" onclick=" return confirm('Da li sigurno brisete?')" class="btn btn-md btn-danger" >Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Short desc</th>
                                        <th>Long desc</th>
                                        <th>Rating</th>
                                        <th>User</th>
                                        <th>Options</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/movies/show.blade.php
@extends('admin.layouts.admin-layout')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    Show Movie
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Title:</label>
                                                    <p>{{$movie->title}}</p>
                                            </div>
                                            <div class="form-group">
                                                <label>Short description
                                                </label>
                                                <p>{{$movie->short_description}}</p>
                                            </div>
                                            <div class="form-group">
                                                <label>Long Description</label>
                                                <p>{{$movie->long_description}}</p>
                                            </div>
                                            <div class="form-group">
                                                <label> Rating </label>
                                                <p>{{$movie->rating}}</p>
                                            </div>
                                            <div class="form-group">
                                                <label>Image</label>
                                                <div class="img">
                                                    <img src="{{asset('images/'.$movie->image_path)}}" style="width: 500px; height: 500px;"/>
                                                </div>
                                            </div>
                                            <a href="{{route('movies.index')}}" class="btn btn-success">Back</a>
                                            <a href="{{$movie->id}}/edit" class="btn btn-md btn-warning">Edit</a>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

@endsection